framework:
    messenger:
        # reset services after consuming messages
        reset_on_message: true

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            send_transaction:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: send_transaction
                    queues:
                        send_transaction:
                            binding_keys:
                                - send_transaction
            send_order_completed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: send_order_completed
                    queues:
                        send_order_completed:
                            binding_keys:
                                - send_order_completed

        routing:
            # Route your messages to the transports
            'App\Component\Message\SendTransactionMessage': send_transaction
            'App\Component\Message\SendCompletedOrderMessage': send_order_completed
