nelmio_api_doc:
    documentation:
        info:
            title: API Documentation (Demo SWAGGER)
            description: Контакты <br />
             - [GitHub](https://github.com/ildarik081)<br />
             - [Репозиторий](https://github.com/ildarik081/order)
            version: 0.0.1
        tags:
        - name: Product
          description: Ручки для работы с продуктами
        - name: Image
          description: Ручки для работы с изображениями
        - name: Cart
          description: Ручки для работы с корзиной
        - name: Order
          description: Ручки для работы с заказом
    areas:
        path_patterns: 
            - ^/api(?!/doc$)
