version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: .docker/dev/php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: "serverName=DevServer"
      WORKING_DIR: /var/www/html
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

  web-server:
    image: nginx:latest
    container_name: web-server
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/dev/web/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    container_name: db
    image: postgres:13-alpine3.15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=order
    ports:
      - ${POSTGRES_ADDRESS:-127.0.0.1:5432}:5432

  db-test:
    container_name: db-test
    image: postgres:13-alpine3.15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=order_test
    ports:
      - ${POSTGRES_ADDRESS:-127.0.0.1:5434}:5434

  amqp:
    image: rabbitmq:3-management-alpine
    container_name: amqp
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
