name: Code analyze

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:	
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PHPCS
        uses: chindit/actions-phpcs@master
        with:
          dir: src/

  phpmd:
    name: PHPMD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          tools: phpmd

      - name: Run PHPMD
        run: phpmd src text --exclude src/Kernel.php controversial,./phpmd.xml

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPStan
        uses: chindit/actions-phpstan@master
        with:
          arguments: 'src/ --level=7'
  
  psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: none

            -   name: Create database
                run: |
                  sudo /etc/init.d/mysql start
                  mysql  -u root -proot -e 'CREATE DATABASE IF NOT EXISTS app_database;'
            -   name: Cache composer dependencies
                uses: actions/cache@v1
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}

            -   name: Run composer install
                run: composer install -n --prefer-dist

            -   name: Prepare Laravel Application
                run: |
                    cp .env.ci .env
                    php artisan key:generate
                    php artisan migrate
            -   name: Generate IDE helper files
                run: |
                    php artisan ide-helper:eloquent
                    php artisan ide-helper:generate
                    php artisan ide-helper:meta
                    php artisan ide-helper:models
            -   name: Run psalm
                run: ./vendor/bin/psalm -c psalm.xml
